module.exports = {
  apps: [
    {
      name: 'digital-shop',
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      cwd: './',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      log_file: './logs/pm2-combined.log',
      time: true,
      merge_logs: true,
    },
    {
      name: 'auto-topup-cron',
      script: './scripts/auto-topup-daemon.js',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        HOST: 'localhost',
      },
      error_file: './logs/cron-error.log',
      out_file: './logs/cron-out.log',
      time: true,
      merge_logs: true,
    },
  ],
};
